name: CICD Demo
on:
 push:
  branches:
   - Priya
 pull_request:
  branches:
   - Priya
jobs:
 build-and-test:
  runs-on: macos-latest
  steps:
  - uses: actions/checkout@v2
  - name: Select Xcode
    run: sudo Xcode-select -switch /Applications/Xcode.app
  - name: Build & Test
    run: xcodebuild clean build test -project CIdemoProject.xcworkspace -scheme CIdemoProject -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.2'
