name: Demo-CI-Test                 

on:    
  push: 
       branches:
            -Priya

jobs:   
  test:
    name: Test
    runs-on: macos-latest.  


    strategy:      
        matrix:  
          destination: [“platform=iOS Simulator,OS=13.2.2,name=iPad Pro 12.9-inch”]


    steps:   
      - name: Checkout
        uses: actions/checkout@Priya


      - name: Build    
        run: |
          xcodebuild clean build -project CIdemoProject.xcodeproj -scheme CIdemoProject -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}


      - name: Test  
        run: |
          xcodebuild clean test -project CIdemoProject.xcodeproj  -scheme CIdemoProjectTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
